services:
  leptos-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kenespartadev-dev
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app/.
      - ~/.aws:/root/.aws:ro
    environment:
      - RUST_LOG=debug
      - LEPTOS_SASS_VERSION=1.93.3
      - AWS_PROFILE=AdministratorAccess-711387133796
    networks:
      - dev-network

volumes:
  cargo-cache:
  target-cache:

networks:
  dev-network:
    driver: bridge
